### ISSUE TITLE
I deployed aida on my server but occur a problem,can you help me?

### ISSUE THREAD

**Issue by iehyxue** [yago-naga/aida#11]
my OS is windows server 2008
RAM 32GB
JDK 1.6
mvn 3.0.5
 
the message is:
E:\workspace\aida>java -Xmx4G -cp target/aida-2.0.4-jar-with-dependencies.jar mp
i.aida.CommandLineDisambiguator -t GRAPH -i "test.txt"
Processing 1 documents with 1 threads.
2015-07-11 10:07:29,245 [pool-1-thread-1] INFO  TokenizerManager:98  - Loading T
okenizer (ssplit, tokenize, pos, ner)
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3wo
rds/english-left3words-distsim.tagger ... done [2.5 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.c
rf.ser.gz ... done [10.7 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.c
rf.ser.gz ... done [7.7 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim
.crf.ser.gz ... done [10.2 sec].
Initializing JollyDayHoliday for sutime
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/defs.sutime.txt
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.sutime.txt

2015-1-11 10:08:01 edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor
appendRules
信息: Ignoring inactive rule: temporal-composite-8:ranges
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.holidays.s
utime.txt
2015-08-11 10:08:02,013 [pool-1-thread-1] INFO  AidaManager:202  - Connecting to
 postgres database postgres@222.22.65.153:5432/wiki
2015-08-11 10:08:02,052 [pool-1-thread-1] INFO  Disambiguator:84  - Disambiguati
ng 'E:\workspace\aida\test.txt' with 1 chunks and 4 mentions.
2015-08-11 10:08:03,853 [pool-2-thread-1] INFO  DataAccessSQLCache$CachingHashMa
p:83  - Caching up to 20000 entities per query type
2015-08-11 10:08:06,433 [pool-2-thread-1] INFO  DataAccessCache:43  - Loading wo
rd caches.
2015-08-11 10:08:06,435 [pool-2-thread-1] INFO  DataAccessCacheTarget:40  - Load
ing WORD_EXPANSION from cache.
2015-08-11 10:08:06,436 [pool-2-thread-1] INFO  DataAccessCacheTarget:40  - Load
ing KEYWORD_COUNT from cache.
2015-08-11 10:08:06,437 [pool-2-thread-1] INFO  DataAccessCache:81  - Done loadi
ng caches.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at mpi.aida.graph.similarity.util.SimilaritySettings.getMentionEntitySim
ilarities(SimilaritySettings.java:277)
        at mpi.aida.graph.similarity.EnsembleMentionEntitySimilarity.init(Ensemb
leMentionEntitySimilarity.java:85)
        at mpi.aida.graph.similarity.EnsembleMentionEntitySimilarity.<init>(Ense
mbleMentionEntitySimilarity.java:69)
        at mpi.aida.graph.GraphGenerator.computeMentionPriorSimL1Distances(Graph
Generator.java:214)
        at mpi.aida.graph.GraphGenerator.generateGraph(GraphGenerator.java:131)
        at mpi.aida.graph.GraphGenerator.run(GraphGenerator.java:79)
        at mpi.aida.ChunkDisambiguator.runGraphDisambiguation(ChunkDisambiguator
.java:125)
        at mpi.aida.ChunkDisambiguator.disambiguate(ChunkDisambiguator.java:69)
        at mpi.aida.ChunkDisambiguator.run(ChunkDisambiguator.java:192)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 12528
        at mpi.aida.access.DataAccessCacheTarget.getData(DataAccessCacheTarget.j
ava:32)
        at mpi.aida.access.DataAccessCache.getKeywordCount(DataAccessCache.java:
108)
        at mpi.aida.access.DataAccess.getKeywordDocumentFrequencies(DataAccess.j
ava:323)
        at mpi.aida.graph.similarity.context.KeyphrasesContext.setupEntities(Key
phrasesContext.java:167)
        at mpi.aida.graph.similarity.context.EntitiesContext.<init>(EntitiesCont
ext.java:30)
        at mpi.aida.graph.similarity.context.KeyphrasesContext.<init>(Keyphrases
Context.java:63)
        ... 16 more
2015-08-11 10:08:06,457 [pool-1-thread-1] INFO  Disambiguator:94  - Document 'E:
\workspace\aida\test.txt' done in 4.4s
HTML generated from JSON representation
Disambiguation for 'E:\workspace\aida\test.txt' done, result written to 'E:\work
space\aida\test.txt.html' in HTML
Mentions and Entities found:
        Mention Entity_id       Entity  Entity Name     URL

the generated html file doesn't have linked entities.

**Comment by hoffart** [comment]
Hi,

could you please paste the content of the file you are trying to process so that we can have a look?

Cheers
Johannes

**Comment by iehyxue** [comment]
Hi,
the content of the file is :When [[Page]] played Kashmir at Knebworth, his Les Paul was uniquely tuned.

Today I tried the latest version 2.1.3, I have already changed the max_connections of postgresql.conf to 1024.But it occured an Error:

[Hikari Housekeeping Timer] ERROR HikariPool:383  - Maximum connection creation retries exceeded

Could you please help me ?

**Comment by hoffart** [comment]
Hi,

I guess you have some of the DB configurations wrong. Please make sure to have host, port, database, user, and pass set correctly (best try it with pgAdmin from the machine you are running it on).

Unfortunately, the DB access code is currently written in a way that Exceptions are not thrown but it simply retries for a connectin. You can try changing the logger settings in 'settings/log4j.properties' from INFO to DEBUG (don't forget to package the jar again afterwards).

Hope this helps,
Johannes

**Comment by iehyxue** [comment]
Hi,hoffart
I changed the Entity Repository to bzcat AIDA_entity_repository_2010-08-17v7.sql.bz2 and it works very well using :
java -Xmx4G -cp target/aida-2.X.X-jar-with-dependencies.jar mpi.aida.CommandLineDisambiguator -t GRAPH -s -i "Einstein was born in Ulm"

but  when I Start the AIDA web service with: mvn jetty:run ,it cannot be accessed at the URL:
http://localhost:8080/aida/service/disambiguate-defaultsettings

it occurs HTTP ERROR 405
Problem accessing /aida/service/disambiguate-defaultsettings. Reason:
Method Not Allowed

Could you please give me some advice?
Xue

**Comment by hoffart** [comment]
Hi Xue,

sorry I don't know why this happens, do you have any log messages in the AIDA service?

Cheers
Johannes

**Comment by pwichmann** [comment]
I experience the same problem.
