### ISSUE TITLE
Build fails first time, pass on second run

### ISSUE THREAD

**Issue by sadovnychyi** [yago-naga/aida#14]
I'm building a docker file which will allow to run AIDA,
but I got an error on `mvn package`.

Funny fact: when I ran it in second time -- the build pass.

So right now my docker contains lines like this: (and its works this way)

```docker
RUN mvn package -X || true
RUN mvn package
```

Full trace log is here with `mvn package` only:
https://registry.hub.docker.com/u/sadovnychyi/aida-docker/build_id/29224/code/bamkkyjpracw2x4wf93t77m/
Full trace log with both (successful build):
https://registry.hub.docker.com/u/sadovnychyi/aida-docker/build_id/29224/code/benyvwtydvf5zzdpeh9omue/

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.710s
[INFO] Finished at: Sat Apr 18 14:35:26 UTC 2015
[INFO] Final Memory: 18M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project aida: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: Could not find artifact org.codehaus.plexus:plexus-component-annotations:jar:1.5.5 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project aida: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: Could not find artifact org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: Could not find artifact org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:82)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: Could not find artifact org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:215)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:353)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:321)
at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:175)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:78)
... 20 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:207)
... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:528)
... 27 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by hoffart** [comment]
Hi, first of all, thanks for trying to build AIDA for docker!

I cannot access the links to the log files you posted. However, running mvn package is not necessary if you do mvn jetty:run afterwards, this will do the build process as well.

The log looks like maven cannot properly resolve the plugins, not sure what could cause this - maybe something is not set up quick enough before the first mvn package call?

**Comment by sadovnychyi** [comment]
Sorry about broken links.
https://gist.github.com/sadovnychyi/fc83b1ff53b7cb80e3c9 -- broken build.
https://gist.github.com/sadovnychyi/773841d0ac00cb3b8ae4 -- successful build.

Am I right that if we will not pre-build it on the docker file -- it will take much more time to run it for the first time?

You can see the sources of docker file here:
https://github.com/sadovnychyi/aida-docker/blob/master/Dockerfile

Thanks for awesome project!
BTW, is there are any google group available where its possible to discuss some things?
I wasn't able to run it on the 50 GB RAM instance due to memory error, only 100 worked (with dMaps).

**Comment by hoffart** [comment]
Thanks for the log, I had a look at the broken build - I gives me the same idea as before, it seems that some core maven plugins are not yet ready. Maybe you can solve this by "waiting a little" before the maven calls are made?

There is no mailing list or google group yet, probably we should set something up - most of the discussion has been happening here until now.

Regarding the memory issues, 50GB should be enough to start even with DMaps, I have run it on internal servers with 48GB with no problems. However, the graph algorithm sometimes needs quite a lot of memory, so without tweaking 48GB are too little. 64GB is comfortable for DMaps and 4 to 8 parallel document threads for processing.

**Comment by sadovnychyi** [comment]
By default graph algorithm is not used, right?
Maybe its some kind of docker limitation or because I've tried to run it only with HTTP API. 64 GB and 4 documents processing in parallel sounds pretty good, much better than I expected. In fact, I didn't saw more than 35 GB of memory usage by running `free` periodically.

It takes minutes to process, well, big document, about 500 kb of plain text, so you say that I can run multiple calls in parallel?

Would be awesome to see other people experience about how to run it.

**Comment by hoffart** [comment]
The graph algorithm is used by default, and the complexity is quadratic in the number of candidate entities, which is correlated to the length of the document. To trade off quality for a bump in speed, you can pass LOCAL as technique ("tech"), which will disable the graph processing. However, we are working on improving the speed even with graph processing, so the performance will get better.

The graph processing is very useful for shorter documents such as news articles, however your size suggests more book size documents, right? Then, LOCAL is perfectly adequate.

If you want to process large collections, the Web Service is probably not the right way to go anyway, have a look at the 'mpi.aida.CommandLineDisambiguator' which is more flexible. However, even the web service can be called in parallel, it should be configured to allow 4 concurrent requests, the others are queued - jetty allows for this. Unfortunately, the jetty version we are using seems to have a problem with the threading, and other jetty versions have class loading issues - we are trying to fix this as soon as possible!

**Comment by sadovnychyi** [comment]
Ok, that explains why it didn't worked with 50 GB.

Thanks a lot for explanations.

However it looks like it should be possible to wrap `mpi.aida.CommandLineDisambiguator` in a simple web server which will accept documents in **batches** for faster processing, but with easy-of-use of the web API.

**Comment by hoffart** [comment]
True, this would be possible, the RequestProcessor that serves the HTTP requests is mostly that. However, the `CommandLineDisambiguator` has more options, as we are using this for processing larger collections mostly. From the architecture point of view, it does not make special use of batches of documents either, it processes all of them sequentially.
