### ISSUE TITLE
No associated tokens

### ISSUE THREAD

**Issue by ZaxCZ** [yago-naga/aida#18]
Hello, it is me again. After updating aida, everyhing worked fine and I started trying to get responses from aida web service using python code. After few attempts I have been successful. But then I started getting weird data, so I tried the curl command from readme again, which didn't work. So I tried the command line example and it fails too, but I think it is best of the three to determine the error from.

I run this `java -Xmx12G -cp target/aida-3.0.4-SNAPSHOT-jar-with-dependencies.jar mpi.aida.CommandLineDisambiguator -t GRAPH -s -i "Einstein was born in Ulm" >> output` with `>> output` due to large amount of the same error. This is what I get in the terminal:
```
Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0,7 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [6,2 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [1,5 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [3,5 sec].
sutime.binder.1.
Initializing JollyDayHoliday for sutime with classpath:edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/defs.sutime.txt
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.sutime.txt
Srp 13, 2015 7:21:19 ODP. edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Ignoring inactive rule: null
Srp 13, 2015 7:21:19 ODP. edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Ignoring inactive rule: temporal-composite-8:ranges
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
Error while processing '/mnt/minerva1/nlp/projects/sec_ners2/aida/aida/Einstein4909962435016010396.txt': Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at mpi.aida.CommandLineDisambiguator$Processor.run(CommandLineDisambiguator.java:661)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

And finally, this is the `>> output`. 
```
Processing 1 documents with 1 threads, ignoring existing .html and .json files.
2015-08-13 19:15:48,494 [pool-1-thread-1] INFO  TokenizerManager:84  - Loading tokenizer of type: ENGLISH_TOKENS
2015-08-13 19:15:48,614 [pool-1-thread-1] INFO  StanfordNER:45  - Initilaizing Stanford NER
2015-08-13 19:16:01,072 [pool-1-thread-1] INFO  AidaManager:152  - Connecting to database xvalen20@localhost:5432/xvalen20
2015-08-13 19:16:01,267 [pool-1-thread-1] INFO  HikariDataSource:77  - HikariCP pool HikariPool-0 is starting.
2015-08-13 19:16:11,129 [pool-2-thread-1] INFO  DataAccessCache:66  - Loading word caches.
2015-08-13 19:16:11,131 [pool-2-thread-1] INFO  DataAccessIntIntCacheTarget:40  - Loading WORD_EXPANSION from cache.
2015-08-13 19:16:11,675 [pool-2-thread-1] INFO  DataAccessIntIntCacheTarget:40  - Loading WORD_CONTRACTION from cache.
2015-08-13 19:16:12,470 [pool-2-thread-1] INFO  DataAccessIntIntCacheTarget:40  - Loading KEYWORD_COUNT from cache.
2015-08-13 19:16:12,787 [pool-2-thread-1] INFO  DataAccessIntIntCacheTarget:40  - Loading BIGRAM_COUNT from cache.
2015-08-13 19:16:13,287 [pool-2-thread-1] INFO  DataAccessCacheTarget:25  - Loading KEYPHRASE_TOKENS from cache.
2015-08-13 19:16:18,469 [pool-2-thread-1] INFO  DataAccessCacheTarget:32  - KEYPHRASE_SOURCES cache file doesn't exist.
2015-08-13 19:16:18,470 [pool-2-thread-1] INFO  DataAccessCacheTarget:37  - Loading KEYPHRASE_SOURCES from DB.
2015-08-13 19:16:18,472 [pool-2-thread-1] INFO  DataAccessCacheTarget:39  - Caching KEYPHRASE_SOURCES to disk.
2015-08-13 19:16:18,473 [pool-2-thread-1] INFO  DataAccessCache:115  - Done loading caches.
2015-08-13 19:16:18,475 [pool-2-thread-1] INFO  DataAccessSQLCache$CachingHashMap:107  - Caching up to 2000 entities per query type
2015-08-13 19:16:48,360 [pool-2-thread-1] ERROR DataAccessSQLCache:252  - Keyphrase : 13527794 has no associated tokens.
2015-08-13 19:16:48,365 [pool-2-thread-1] ERROR DataAccessSQLCache:252  - Keyphrase : 11574869 has no associated tokens.
2015-08-13 19:16:48,366 [pool-2-thread-1] ERROR DataAccessSQLCache:252  - Keyphrase : 13139043 has no associated tokens.
2015-08-13 19:16:48,366 [pool-2-thread-1] ERROR DataAccessSQLCache:252  - Keyphrase : 11156018 has no associated tokens.
.
.
.
.
.   There is 668 of these lines. I have cut them out for better clarity.
.
.
.
2015-08-13 19:16:48,518 [pool-2-thread-1] ERROR DataAccessSQLCache:252  - Keyphrase : 359200 has no associated tokens.
2015-08-13 19:16:48,518 [pool-2-thread-1] ERROR DataAccessSQLCache:252  - Keyphrase : 1575640 has no associated tokens.
2015-08-13 19:16:48,518 [pool-2-thread-1] ERROR DataAccessSQLCache:252  - Keyphrase : 13152568 has no associated tokens.
2015-08-13 19:16:48,518 [pool-2-thread-1] ERROR DataAccessSQLCache:252  - Keyphrase : 11250479 has no associated tokens.
2015-08-13 19:16:48,552 [pool-2-thread-1] INFO  DataAccessSQLCache$CachingHashMap:107  - Caching up to 2000 entities per query type
Exception while processing '/mnt/minerva1/nlp/projects/sec_ners2/aida/aida/Einstein7230336779346730626.txt': java.lang.reflect.InvocationTargetException
Error while processing : /mnt/minerva1/nlp/projects/sec_ners2/aida/aida/Einstein7230336779346730626.txt. Adding to errored list (1)
Disambiguation for '/mnt/minerva1/nlp/projects/sec_ners2/aida/aida/Einstein7230336779346730626.txt' done.
```

I suspect, that this is problem of the database, not aida. I have dropped the database and imported it several times (even downloaded it few times, to be sure, both the new bigger one and the default one in readme), but with no success. However, I have noticed this error when I import it: 
```
CREATE EXTENSION
ERROR:  must be owner of extension plpgsql
```

`CREATE LANGUAGE plpgsql` didn't help. 

I will continue trying to solve this, but I thought you could provide some insight and at least confirm, that the issue is with our database. Thanks again.

**Comment by hoffart** [comment]
Hi,

make sure to delete all .cache files in the AIDA root/working directory, then try to run the example again. I think this might be due to a corrupt cache file. Let me know if this helped or now.

Cheers
Johannes

**Comment by ZaxCZ** [comment]
It worked, thanks a lot!
