### ISSUE TITLE
Settings file parser can't handle trailing whitespace.

### ISSUE THREAD

**Issue by kumik** [yago-naga/aida#20]
Aid fails if there is a trailing whitespace in the settings/database_aida.properties file for the database port number property.

It might be prudent to trim whitespace from both sides of an input string.

```
2016-01-08 13:11:00,139 [pool-1-thread-1] ERROR AidaManager:158  - Error connecting to the database: java.lang.NumberFormatException: For input string: "5432 "
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "5432 "
	at com.zaxxer.hikari.util.PropertyBeanSetter.setProperty(PropertyBeanSetter.java:145)
	at com.zaxxer.hikari.util.PropertyBeanSetter.setTargetFromProperties(PropertyBeanSetter.java:58)
	at com.zaxxer.hikari.pool.HikariPool.initializeDataSource(HikariPool.java:500)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:134)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:99)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:78)
	at mpi.aida.AidaManager.getConnectionForNameAndProperties(AidaManager.java:155)
	at mpi.aida.AidaManager.getConnectionForDatabase(AidaManager.java:136)
	at mpi.aida.access.DataAccessSQL.getIdsForWords(DataAccessSQL.java:839)
	at mpi.aida.access.DataAccess.getIdsForWords(DataAccess.java:266)
	at mpi.aida.data.Context.<init>(Context.java:27)
	at mpi.aida.data.PreparedInputChunk.createContextFromTokens(PreparedInputChunk.java:45)
	at mpi.aida.data.PreparedInputChunk.<init>(PreparedInputChunk.java:25)
	at mpi.aida.preparation.documentchunking.SingleChunkDocumentChunker.process(SingleChunkDocumentChunker.java:16)
	at mpi.aida.preparator.Preparator.prepareInputData(Preparator.java:120)
	at mpi.aida.preparator.inputformat.PlainPreparatorInputFormat.prepare(PlainPreparatorInputFormat.java:90)
	at mpi.aida.preparator.Preparator.prepare(Preparator.java:95)
	at mpi.aida.CommandLineDisambiguator$Processor.run(CommandLineDisambiguator.java:588)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bingo20145** [comment]
Excuse me,  I want to know how to use testdata?

**Comment by bingo20145** [comment]
Testdata not contains document, so I don't know how to use it
