### ISSUE TITLE
java.lang.NullPointerException despite command line test

### ISSUE THREAD

**Issue by pwichmann** [yago-naga/aida#25]
Many thanks for - what I hope - is an amazing software.

Unfortunately, I ran into the following issue.
Any idea what could have gone wrong? (I used the parameter LOCAL here but had used GRAPH before with identical result).

The system is as follows:
* Ubuntu 16.04 LTS
* Postgres 9.5
* Default aida.properties
* database_aida.properties:
  * dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
  * dataSource.serverName = localhost
  * dataSource.databaseName = aida
  * dataSource.user = postgres
  * dataSource.password = [redacted]
  * dataSource.portNumber = 5432
   * maximumPoolSize=5

```
/Yago/aida$ java -Xmx12G -cp target/aida-3.0.5-SNAPSHOT-jar-with-dependencies.jar mpi.aida.CommandLineDisambiguator -t LOCAL -s -i "Einstein was born in Ulm"

Processing 1 documents with 1 threads, ignoring existing .html and .json files.
2017-06-13 20:56:01,806 [pool-1-thread-1] INFO  TokenizerManager:84  - Loading tokenizer of type: ENGLISH_TOKENS
Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
2017-06-13 20:56:01,862 [pool-1-thread-1] INFO  StanfordNER:45  - Initilaizing Stanford NER
Adding annotator tokenize
TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
Adding annotator ssplit
Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.4 sec].
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [1.6 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.8 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [2.0 sec].
sutime.binder.1.
Initializing JollyDayHoliday for sutime with classpath:edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/defs.sutime.txt
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.sutime.txt
Jun 13, 2017 8:56:06 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Ignoring inactive rule: null
Jun 13, 2017 8:56:06 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Ignoring inactive rule: temporal-composite-8:ranges
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
2017-06-13 20:56:07,052 [pool-1-thread-1] INFO  AidaManager:152  - Connecting to database postgres@localhost:5432/aida
2017-06-13 20:56:07,157 [pool-1-thread-1] INFO  HikariDataSource:77  - HikariCP pool HikariPool-0 is starting.
2017-06-13 20:56:37,165 [pool-1-thread-1] ERROR DataAccessSQL:859  - Timeout of 30000ms encountered waiting for connection.
Error while processing '/home/pascal/Documents/Yago/aida/Einstein5206990401752353244.txt': null
java.lang.NullPointerException
	at mpi.aida.CommandLineDisambiguator$Processor.run(CommandLineDisambiguator.java:624)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hoffart** [comment]
Hi there,

as DataAccessSQL is timing out, it looks like your database connection is not working properly. Double-check this and make sure to put the right properties file on the classpath.

Cheers
Johannes

**Comment by pwichmann** [comment]
You are totally right. I am sorry. I had problems with my database - it was totally unrelated to Yago/Aida.
