### ISSUE TITLE
Hands-On API Example not Connecting to PostgreSQL

### ISSUE THREAD

**Issue by Agupta00** [yago-naga/aida#26]
Hi, 

I am trying to run the Hands-On API Example with the input string: String inputText = "When [[Page]] played Kashmir at Knebworth, his Les Paul was uniquely tuned.";

I have checked to make sure the Data Base values are correct.
When I run I get the following error..

2017-07-18 18:04:13,776 [main] INFO  AidaManager:152  - Connecting to database <akul>@<Host:Port>:5432/<repo>
2017-07-18 18:04:14,002 [main] INFO  HikariDataSource:77  - HikariCP pool HikariPool-0 is starting.
2017-07-18 18:04:44,023 [main] ERROR DataAccessSQL:860  - Timeout of 30000ms encountered waiting for connection.
Exception in thread "main" 
java.lang.NullPointerException
	at mpi.aida.AidaManager.releaseConnection(AidaManager.java:191)
	at mpi.aida.access.DataAccessSQL.getIdsForWords(DataAccessSQL.java:863)
	at mpi.aida.access.DataAccess.getIdsForWords(DataAccess.java:266)
	at mpi.aida.data.Context.<init>(Context.java:27)
	at mpi.aida.data.PreparedInputChunk.createContextFromTokens(PreparedInputChunk.java:45)
	at mpi.aida.data.PreparedInputChunk.<init>(PreparedInputChunk.java:25)
	at mpi.aida.preparation.documentchunking.SingleChunkDocumentChunker.process(SingleChunkDocumentChunker.java:17)
	at mpi.aida.preparator.Preparator.prepareInputData(Preparator.java:119)
	at mpi.aida.preparator.inputformat.PlainPreparatorInputFormat.prepare(PlainPreparatorInputFormat.java:90)
	at mpi.aida.preparator.Preparator.prepare(Preparator.java:94)
	at mpi.aida.preparator.Preparator.prepare(Preparator.java:44)
	at Driver2.main(Driver2.java:23)

Please let me know what could be the problem.

**Comment by hoffart** [comment]
Hi,

the fact that the connection pool of the SQL access is timing out has as most likely cause that the database is not accessible. Make sure that not only credentials are correct but also potential firewall settings.

Cheers
Johannes

**Comment by Agupta00** [comment]
Fixed the problem. Simply forgot to remove the brakets in the aida_database file. Thanks!
